### ISSUE TITLE
Add Transaction "cleared" field

### ISSUE THREAD

**Issue by mr-ned** [sebastienbarbier/seven23#110]
When performing an account reconciliation, it would be helpful to have an item on each transaction that indicates if it has cleared or is still pending. This would result in more accurate information / better visibility into account balances in seven23. This field could be called 'cleared' and be a boolean value.

True = Transaction is marked as 'cleared' on online bank accounts, money has left the account and transferred to the payee.
False = Transaction is marked as 'uncleared' on online bank accounts, money has not quite left the account but will soon. Unless specified, this should be the default. A checkbox would suffice on the transaction form, I think.

Something to consider:
account balances will need two balances that are tracked. One that is the "working" balance versus the "cleared" balance. The "working" balance will be the balance _including_ all pending transactions marked as cleared and the "cleared" balance would be the balance _without_ the pending transactions.

Use case example:
account1 had a previous balance of $100
I spend $10 at 'The Best Grocery Store' and put the transaction into seven23.
This results in account1 having one 'pending' transaction of $10
'working' balance would be $90
'cleared' balance would be $100
Once I've done an account reconciliation, and subsequently marked the transaction as 'cleared', the 'working' and 'cleared' balance would be $90.

**Comment by sebastienbarbier** [comment]
This will be implemented in v2.0 coming next month

**Comment by sebastienbarbier** [comment]
Dev is done, will be in next release.
