### ISSUE TITLE
Transaction Date Incorrect Upon Submission and Editing

### ISSUE THREAD

**Issue by steveny9911** [sebastienbarbier/seven23#43]
I noticed an issue regarding transaction date being wrong.

**Steps to reproduce**

- Locally no sync (running only through `app.seven23.io`), the updated date (console logged and displayed on frontend) is one day ahead of the selected date (editing and submitting on the left)
  - Running Chrome Mac, and also issue on Chrome Android
  - Add a new transaction with date of `Aug 15, 2020`, then submit
  - Date shown on the frontend is `Aug 13, 2020` which is two day ahead of the submitted date
  - Edit the transaction back to `Aug 15, 2020`, then submit 
  - Date shown in the frontend is `Aug 14, 2020` (attached screenshot with console log) which is one day ahead of the submitted date
- Deployed on Heroku, it seems like I am having the same issue, but sometimes it will be three- or four-days ahead. 
  - Once synced, the date does not change, and appears to be the same across all sessions

![Screen Shot 2020-08-17 at 10 52 07 PM](https://user-images.githubusercontent.com/8460976/90475462-544d4b00-e0dc-11ea-82c8-88af3b9143e2.png)

Let me know if this is reproducible anywhere.

**Comment by sebastienbarbier** [comment]
This is a bug regression from the client regarding the way it handle timzones within momentJS. I could reproduce, changing my local timezone from a day before current UTC, I believe this issue was only tested with hours before UTC not a day, not great 😥. 
If we are lucky, stored date should still be UTC and fix will be able to maintain data integrity without requiring to manually fix them 🙌.
Will put this issue as critical, and be top priority before any new dev, thanks so much for reporting it.

**Comment by sebastienbarbier** [comment]
After more testing, dates are stored with the wrong day within indexedDB, data integrity is compromised 😥.

**Comment by sebastienbarbier** [comment]
Changing timezone on local machine, this issue is caused by a javascript cast from string which should not be done : 
```
new Date(2020, 07, 01)
Date Sat Aug 01 2020 00:00:00 GMT-0900 (heure d’été d’Hawaii - Aléoutiennes)

new Date('2020-08-01')
Date Fri Jul 31 2020 15:00:00 GMT-0900 (heure d’été d’Hawaii - Aléoutiennes)
```
Code needs to be updated using a proper cast/convert function. Work in progress 🙌

**Comment by sebastienbarbier** [comment]
3 weeks for a fix 🙈, was way bigger than expected as I had to refactor the all date handling.
Should all be good now, dates are string based and generated in local timezone instead of having some weird UTC references. 👍.
Thanks a lot for the feedback and helping to make a better app.

**Comment by steveny9911** [comment]
This is amazing! Thanks so much for the fix!
